[project]
name = "merlin_socials"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "streamlit",
    "pandas",
    "numpy",
    "streamlit-tts>=0.0.8",
    "audioop-lts>=0.2.2",
    "dotenv>=0.9.9",
    "gtts>=2.5.4",
]
